# A short, descriptive name of this building block collection
name: ISO 19115 JSON Schema options

# Short abstract for this collection (optional)
abstract: |
  This repository contains various test cases and examples of previous work to explore options for encoding ISO 19115 using JSON

# Description for this collection (optional)
description: |
  Each BuildingBlock will start using the original proposals available, but should be "refactored" to remove content duplicated from other specifications, to be replaced by references to building blocks for those specifications.
  
  This will ensure compliance - but also make the relationships transparent. It will also be easier to maintain.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.metacat.iso19115

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available